#ifndef INITIALLIGHTS_GLOBAL_H
#define INITIALLIGHTS_GLOBAL_H

#include <QtCore/qglobal.h>
#ifdef _MSC_VER
    #if defined(INITIALLIGHTS_LIBRARY)
    #  define INITIALLIGHTSSHARED_EXPORT
    #else
    #  define INITIALLIGHTSSHARED_EXPORT
    #endif
#else
    #if defined(INITIALLIGHTS_LIBRARY)
    #  define INITIALLIGHTSSHARED_EXPORT Q_DECL_EXPORT
    #  define INITIALLIGHTSSHARED_EXPORT
    #else
    #  define INITIALLIGHTSSHARED_EXPORT Q_DECL_IMPORT
    #  define INITIALLIGHTSSHARED_EXPORT
    #endif
#endif

#define SCENE_COUNT 6

#endif // INITIALLIGHTS_GLOBAL_H
